const list = [
  {
    id: 1,
    title: "DJI Mini 3 Pro (Drone with 4K/60fps Video)",
    author: "RC Quadcopters & Multirotors by DJI",
    price: 909,
    img: "https://m.media-amazon.com/images/I/61Y1P6uIRFL._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Canon EOS Rebel T7 DSLR Camera with 18-55mm",
    author: "DSLR Cameras by Canon",
    price: 479,
    img: "https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "GoPro HERO10 Black - Waterproof",
    author: " Action Video Cameras by GoPro",
    price: 399,
    img: "https://m.media-amazon.com/images/I/61p2fYdYP+L._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Xbox Series X",
    author: "Series X",
    price: 399,
    img: "https://m.media-amazon.com/images/I/61JGKhqxHxL._SX522_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "PS5 Console- Horizon Forbidden West Bundle",
    author:  "playstation",
    price: 549,
    img: "https://m.media-amazon.com/images/I/71fa5+U25cL._SX522_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Oculus Quest 2 - Advanced All-In-One",
    author: " Oculus Quest 2",
    price: 349,
    img: "https://m.media-amazon.com/images/I/61kwRNPtMpL._SX522_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Razer BlackShark V2 Gaming ",
    author: "Headsets by Razer",
    price: 74,
    img: "https://m.media-amazon.com/images/I/61wrOi+03FL._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Razer DeathAdder V2 Gaming Mouse",
    author: " Mice by Razer",
    price: 42,
    img: "https://m.media-amazon.com/images/I/61doJ9AKCPL._AC_SX679_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Razer Huntsman Tournament Edition TKL Tenkeyless Gaming Keyboard ",
    author: "Razer Store",
    price: 69,
    img: "https://m.media-amazon.com/images/I/71GVODjIEJL._AC_SX679_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "SkyTech Shadow 3.0 Gaming Computer PC Desktop - Ryzen 5 3600 6-Core 3.6GHz, GTX 1660 Super 6G",
    author: "Skytech Gaming Store",
    price: 999,
    img: "https://m.media-amazon.com/images/I/81cUusLl06S._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "MSI Pulse GL66 Gaming Laptop: 15.6 144Hz FHD 1080p Display, Intel Core i7-11800H, NVIDIA GeForce RTX 3070",
    author: "MSI",
    price: 1600,
    img: "https://m.media-amazon.com/images/I/61Ze2wc9nyS._AC_SX466_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Razer Iskur Gaming Chair: Ergonomic Lumbar Support",
    author: "Razer Store",
    price: 469,
    img: "https://m.media-amazon.com/images/I/619-kxYmG1L._AC_SL1500_.jpg",
    amount: 1,
  },
];

export default list;
